version: '3'
services:
    db:
      image: mysql:5.7.19
      container_name: mysql
      expose:
        - 3306
      environment:
          MYSQL_DATABASE: gu
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_USER: root
      volumes:
         - ./db/data:/var/lib/mysql
         - ./db/conf.d/:/etc/mysql/conf.d
    web:
       build: .
       restart: always
       command: uwsgi --ini ./uwsgi.ini
       volumes:
          - .:/site
#      和nginx配合使用就不需要设置端口映射,uwsgi单独使用的话需要配置
#       ports:
#          - 9000:8000
       depends_on:
          - db
       links:
          - db
    nginx:
      image: nginx
      container_name: nginx-container
      restart: always
      depends_on:
        - web
      links:
        - web
      ports:
        - 8080:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./guproject/static:/opt/nginx/static

